NetEFPruebaInicial/Models/ErrorViewModel.cs
namespace NetEFPruebaInicial.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetEFPruebaInicial/Controllers/EspecieController.cs
using Microsoft.AspNetCore.Mvc;
using NetEFPruebaInicial.Logica;
using NetEFPruebaInicial.Data.Entidades;
using System.Reflection.PortableExecutable;
using System.Data.Entity.Core.Metadata.Edm;

namespace NetEFPruebaInicial.Controllers
{
    public class EspecieController : Controller
    {
        private IEspecieService _especieService;

        public EspecieController (IEspecieService especieService)
        {
            _especieService = especieService;  
        }

        [HttpGet]
        public IActionResult Alta()
        {
            ViewBag.TipoEspecies = _especieService.ObtenerTE();
            return View();
        }

        [HttpPost]
        public IActionResult Alta(Especie especie)
        {
            _especieService.Insertar(especie);
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public IActionResult Listar()
        {

            ViewBag.TipoEspecies = _especieService.ObtenerTE();
            return View(_especieService.ObtenerTodos(0));
        }

        [HttpPost]
        public IActionResult Listar(Tipoespecie tipoEspecie)
        {
            int idTE = tipoEspecie.IdTipoEspecie;
            ViewBag.TipoEspecies = _especieService.ObtenerTE();
            return View(_especieService.ObtenerTodos(idTE));
        }

        public IActionResult Eliminar(int id)
        {
            Especie esp = _especieService.GetById(id);
            if (esp != null)
            {
                _especieService.Eliminar(id);
            }
            return RedirectToAction("Listar");
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.TipoEspecies = _especieService.ObtenerTE();
            Especie esp = _especieService.GetById(id);
            if (esp!=null)
            {
                return View(esp);
            }
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public IActionResult Edit(Especie especie)
        {
            _especieService.Modificar(especie);
            return RedirectToAction("Listar");
        }

    }
}

NetEFPruebaInicial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NetEFPruebaInicial.Models;
using System.Diagnostics;

namespace NetEFPruebaInicial.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetEFPruebaInicial/Views/Especie/Alta.cshtml
@using NetEFPruebaInicial.Data.Entidades;
@model Especie
@{
}

<form action="/Especie/Alta" method="post">
    <div>
        Nombre: <input type="text" name="Nombre" />
    </div>
    <div>
        Peso Promedio: <input type="number" name="PesoPromedio" />
    </div>
    <div>
        Edad Promedio: <input type="number" name="EdadPromedio" />
    </div>
    <div>
        Tipo Especie: <select name="IdTipoEspecie">
            @foreach (Tipoespecie te in ViewBag.TipoEspecies)
            {
                <option value=@te.IdTipoEspecie>@te.Nombre</option>
            }
        </select>
    </div>
    <input type="submit" value="Agregar" />

</form>

NetEFPruebaInicial/Views/Especie/Edit.cshtml
@model NetEFPruebaInicial.Data.Entidades.Especie;
@{
}

<form action="/Especie/Edit" method="post">
    <div>
        <input type="number" name="IdEspecie" value="@Model.IdEspecie" hidden />
    </div>
    <div>
        Nombre: <input type="text" name="Nombre" value="@Model.Nombre"/>
    </div>
    <div>
        Peso Promedio: <input type="decimal" name="PesoPromedio" value="@Model.PesoPromedio" />
    </div>
    <div>
        Edad Promedio: <input type="number" name="EdadPromedio" value="@Model.EdadPromedio" />
    </div>
    <div>
        Tipo Especie: <select name="IdTipoEspecie">
            @foreach (var te in ViewBag.TipoEspecies)
            {
                if(@te.IdTipoEspecie==Model.IdTipoEspecie){
                    <option value=@te.IdTipoEspecie selected>@te.Nombre</option>
                }else{
                    <option value=@te.IdTipoEspecie>@te.Nombre</option>
                }
                
            }
        </select>
    </div>
    <input type="submit" value="Modificar" />

</form>

NetEFPruebaInicial/Views/Especie/Listar.cshtml
@using NetEFPruebaInicial.Data.Entidades;
@model List<Especie>

<form action="/Especie/Listar" method="post">
    Filtrar :<select name="IdTipoEspecie">
        @foreach (Tipoespecie te in ViewBag.TipoEspecies)
        {
            <option value=@te.IdTipoEspecie>@te.Nombre</option>
        }
        <option value=0 selected>Todas</option>
    </select>

    <input type="submit" value="Aplicar Filtro" />
</form>

<table>
   <tr>
       <th>Id</th>
       <th>Nombre</th>
       <th>Tipo Especie</th>
       <th>Peso Promedio</th>
       <th>Edad Promedio</th>
       <th>Eliminar</th>
   </tr>
   @foreach (var item in Model)
   {
        <tr>
            <td>@item.IdEspecie</td>
            <td><a href="/Especie/Edit/@item.IdEspecie">@item.Nombre</a></td>
            @foreach (var te in ViewBag.TipoEspecies)
            {
                if(@te.IdTipoEspecie==@item.IdTipoEspecie){
                    <td>@te.Nombre</td>
                }
            }
            <td>@item.PesoPromedio</td>
            <td>@item.EdadPromedio</td>
            <td><a href="/Especie/Eliminar/@item.IdEspecie">Eliminar</a></td>
        </tr>
    }
</table>

NetEFPruebaInicial/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetEFPruebaInicial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetEFPruebaInicial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetEFPruebaInicial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetEFPruebaInicial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especie" asp-action="Listar">Listar Especies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Especie" asp-action="Alta">Agregar Especie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NetEFPruebaInicial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>